[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
cn-font-proto = { version = "0.1.0", path = "../../crates/proto" }
cn-font-split = { version = "7.0.0", path = "../.." }
libc = "0.2.165"
prost = "0.13.3"

[lib]
crate-type = ["cdylib"]
