name: release-rust-core

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version number'
                required: true
                default: '7.0.0'

jobs:
    build:
        #运行的环境
        runs-on: ubuntu-24.04
        env:
            TZ: Asia/Shanghai
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Environment
              run: |
                  sudo apt update
                  sudo apt upgrade
                  sudo apt install -y llvm clang pkg-config libssl-dev protobuf-compiler
           
            - name: Setup WASI Environment
              working-directory: ./packages/subsets-rs
              run: |
                  sudo sh ./.devcontainer/wasi-install.sh
                  sudo sh ./.devcontainer/wasm-opt-install.sh
            - name: Install latest stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: Update Rust
              run: /home/runner/.cargo/bin/rustup  target add wasm32-wasip1


            - name: Build Node
              working-directory: ./packages/subsets-rs/crates/lang_unicodes
              run: |
                 npm i
                 npm run build
            - name: Build
              working-directory: ./packages/subsets-rs/packages/wasm-edge
              run: |
                  export WASI_SYSROOT="/opt/wasi-sdk/wasi-sdk-24.0-x86_64-linux/share/wasi-sysroot/"
                  export PATH=$PATH:/opt/binaryen/binaryen-version_119/bin
                  sh build-wasi.sh
            - name: Rename Package
              working-directory: ./packages/subsets-rs
              run: |
                  mv ./target/wasm32-wasip1/release/wasm_edge.wasm ./target/wasm32-wasip1/release/cn-font-split-${{ github.event.inputs.version }}-wasm32-wasi.wasm
                  mv ./target/wasm32-wasip1/release/wasm_edge.Oz.wasm ./target/wasm32-wasip1/release/cn-font-split-${{ github.event.inputs.version }}-wasm32-wasi.Oz.wasm
            - name: Create Release
              uses: actions/create-release@v1
              id: create_release
              with:
                tag_name: ${{ github.event.inputs.version }}
                release_name: Release ${{ github.event.inputs.version }}
                body: |
                  Release ${{ github.event.inputs.version }}
                draft: false
                prerelease: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Upload Release Wasm Oz
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }} 
                asset_path: ./packages/subsets-rs/target/wasm32-wasip1/release/cn-font-split-${{ github.event.inputs.version }}-wasm32-wasi.Oz.wasm
                asset_name: cn-font-split-${{ github.event.inputs.version }}-wasm32-wasi.Oz.wasm
                asset_content_type: application/octet-stream
            - name: Upload Release Wasm
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }} 
                asset_path: ./packages/subsets-rs/target/wasm32-wasip1/release/cn-font-split-${{ github.event.inputs.version }}-wasm32-wasi.wasm
                asset_name: cn-font-split-${{ github.event.inputs.version }}-wasm32-wasi.wasm
                asset_content_type: application/octet-stream
            